# permissions for end users to view alpines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alpine-viewer-role
rules:
- apiGroups:
  - staight.sqf.io
  resources:
  - alpines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - staight.sqf.io
  resources:
  - alpines/status
  verbs:
  - get
